### ISSUE TITLE
OpenSSL encryption/decryption doesn't use `fileb` urls.

### ISSUE THREAD

**Issue by cransom** [matchilling/aws-kms-boilerplate#1]
https://github.com/matchilling/aws-kms-boilerplate/blob/98e7b77b124e77207251188aed1814ce93c93906/bin/decrypt#L66

The documentation and scripts imply that the key files are being used to encrypt/decrypt, however the literal string supplied to `-k` is being used. This ignores any usage of KMS and effectively is a static encryption of files based on path.

**Comment by matchilling** [comment]
@cransom thanks for your comment and sorry for the delayed reply. `aws kms` is being leveraged to generate the data key based on the given master key. The data key is then used as a passphrase in the `openssl enc` call. The reason why we don't use the master key for encryption and decryption can be read up in the [blog post](https://www.matchilling.com/storing-security-sensitive-data-using-aws-kms-and-openssl/).

**Comment by cransom** [comment]
Yes, I understand that completely. However, in your call to openssl, you use a url that the binary doesn't parse as a path.

From https://wiki.openssl.org/index.php/Enc#Options
```
-k password, -kfile filename
Both option are used to specify a password or a file containing the password which is used for key derivation. However they are deprecated. You should use the -pass option instead. The equivalents are -pass pass:password and -pass: pass:filename respectively.
```
The data key is being generated and then ignored because the key/password is just the file name, not the file content.

**Comment by matchilling** [comment]
Ahh ok, got you :speak_no_evil:. Fixed it [here](https://github.com/matchilling/aws-kms-boilerplate/commit/2f2c23ed0d4138242c9254b082142ade6fcebe60).
